"""Add permission fields to listings table

Revision ID: 58fde37a9b74
Revises: 5409b5ea11f4
Create Date: 2025-07-19 02:18:25.083556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58fde37a9b74'
down_revision: Union[str, Sequence[str], None] = '5409b5ea11f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Eğer sütunlar boolean ise integer'a çevir
    op.alter_column('listings', 'allow_events', type_=sa.Integer(), postgresql_using='allow_events::integer')
    op.alter_column('listings', 'allow_smoking', type_=sa.Integer(), postgresql_using='allow_smoking::integer')
    op.alter_column('listings', 'allow_commercial_photo', type_=sa.Integer(), postgresql_using='allow_commercial_photo::integer')
    op.add_column('listings', sa.Column('max_guests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'allow_events', type_=sa.Boolean(), postgresql_using='allow_events::boolean')
    op.alter_column('listings', 'allow_smoking', type_=sa.Boolean(), postgresql_using='allow_smoking::boolean')
    op.alter_column('listings', 'allow_commercial_photo', type_=sa.Boolean(), postgresql_using='allow_commercial_photo::boolean')
    op.drop_column('listings', 'max_guests')
    # ### end Alembic commands ###
