"""Add permission fields to listings table

Revision ID: 58fde37a9b74
Revises: 5409b5ea11f4
Create Date: 2025-07-19 02:18:25.083556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58fde37a9b74'
down_revision: Union[str, Sequence[str], None] = '5409b5ea11f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Yeni kolonları ekle (boolean olarak)
    op.add_column('listings', sa.Column('allow_events', sa.Boolean(), nullable=True, default=False))
    op.add_column('listings', sa.Column('allow_smoking', sa.Boolean(), nullable=True, default=False))
    op.add_column('listings', sa.Column('allow_commercial_photo', sa.Boolean(), nullable=True, default=False))
    op.add_column('listings', sa.Column('max_guests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'max_guests')
    op.drop_column('listings', 'allow_commercial_photo')
    op.drop_column('listings', 'allow_smoking')
    op.drop_column('listings', 'allow_events')
    # ### end Alembic commands ###
