"""add_room_bed_bathroom_count_to_listings

Revision ID: b8468572a309
Revises: fd0b8b232a99
Create Date: 2025-07-22 04:01:11.903275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8468572a309'
down_revision: Union[str, Sequence[str], None] = 'fd0b8b232a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'amenities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('amenities', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
